name: Flutter Build

on:
  # push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: 'android'
            target-platform: 'android-arm64'
          - os: ubuntu-latest
            platform: 'linux'
          - os: windows-latest
            platform: 'windows'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.flutter
          key: flutter-sdk-${{ runner.os }}-${{ hashFiles('.github/workflows/flutter_version') }}
          restore-keys: |
            flutter-sdk-${{ runner.os }}-
  
      - name: Install Flutter (Windows)
        if: runner.os == 'Windows'
        run: |
          $FLUTTER = "$HOME/.flutter"
          echo "FLUTTER=$FLUTTER" | Out-File -Append -Encoding ASCII -FilePath $env:GITHUB_ENV
          echo "$FLUTTER/bin" | Out-File -Append -Encoding ASCII -FilePath $env:GITHUB_PATH
          if (Test-Path "$FLUTTER/bin/flutter") {
            Write-Host "Using cached Flutter SDK"
          }
          else {
            if (Test-Path "$FLUTTER") {
              Remove-Item "$FLUTTER" -Force -Recurse -ErrorAction SilentlyContinue
            }
            git clone https://github.com/flutter/flutter.git -b stable "$FLUTTER"
          }
        shell: powershell
    
      - name: Install Flutter (Linux)
        if: runner.os == 'Linux'
        run: |
          FLUTTER="$HOME/.flutter"
          echo "FLUTTER=$FLUTTER" >> $GITHUB_ENV
          echo "$FLUTTER/bin" >> $GITHUB_PATH
          if [ ! -f "$FLUTTER/bin/flutter" ]; then
            rm -rf "$FLUTTER"
            git clone https://github.com/flutter/flutter.git -b stable "$FLUTTER"
          else
            echo "Using cached Flutter SDK"
          fi
        shell: bash
  
      - name: Cache Linux Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
            
      - name: Cache Windows Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            %USERPROFILE%\.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Cache Android SDK Build-Tools
        uses: actions/cache@v3
        with:
          path: |
           /usr/local/lib/android/sdk/build-tools
          key: build-tools-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock', '.github/workflows/flutter_version') }}
          restore-keys: |
            build-tools-${{ runner.os }}-

      - name: Cache Android SDK Platforms
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/lib/android/sdk/platforms
          key: platforms-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock', '.github/workflows/flutter_version') }}
          restore-keys: |
            platforms-${{ runner.os }}-

      - name: Cache Win Build SDK 
        uses: actions/cache@v3
        with:
          path: |
            **/windows-x64-debug/windows-x64-flutter
            **/windows-x64/flutter-cpp-client-wrapper
            **/windows-x64-profile/windows-x64-flutter
            **/windows-x64-release/windows-x64-flutter
          key: win-flutter-build-sdk-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock', '.github/workflows/flutter_version') }}
          restore-keys: |
            platforms-${{ runner.os }}-
            
      - name: Get Flutter packages
        run: flutter pub get
        
      - name: Build APK
        if: matrix.platform == 'android' && matrix['target-platform'] == 'android-arm64'
        run: flutter build apk --release --target-platform android-arm64

      # - name: Build App Bundle
      #   if: matrix.platform == 'android'
      #   run: flutter build appbundle --release

      - name: Upload APK Artifact
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v3
        with:
          name: android-app
          path: |
            build/app/outputs/flutter-apk/app-release.apk
          # build/app/outputs/bundle/release/app-release.aab

      - name: Setup Linux dependencies
        if:  matrix.platform == 'linux'
        run: |
            sudo apt-get update && sudo apt-get install -y cmake ninja-build clang pkg-config libgtk-3-dev
        shell: bash
        
      - name: Build Linux
        if: matrix.platform == 'linux'
        run: flutter build linux --release
        
      - name: Upload Linux Artifact
        if: matrix.platform == 'linux'
        uses: actions/upload-artifact@v3
        with:
          name: linux-app
          path: build/linux/*
        
      - name: Build Windows
        if: matrix.platform == 'windows'
        run: flutter build windows --release

      - name: Search and print windows-x64-flutter path
        run: |
          $searchRoot = "C:\\" 
          $searchResults = Get-ChildItem -Path $searchRoot -Filter "windows-x64-flutter*" -Recurse -ErrorAction SilentlyContinue -Force
          foreach ($result in $searchResults) {
            if ($result.FullName -like "*windows-x64-debug*") {
              Write-Host "Found path: $($result.FullName)"
            }
          }
        shell: pwsh

      - name: Upload Windows Artifact
        if: matrix.platform == 'windows'
        uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: build/windows/x64/runner/Release/*
