name: Flutter Build

on:
  push:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.16.9'

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: 'android'
            target-platform: 'android-arm64'
          - os: ubuntu-latest
            platform: 'linux'
          - os: windows-latest
            platform: 'windows'
          - os: macos-latest
            platform: 'ios'
          - os: macos-latest
            platform: 'macos'

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      
      - run: flutter pub get

      - name: Build for Android
        if: matrix.platform == 'android'
        run: flutter build apk --release --target-platform ${{ matrix.target-platform }}

      - name: Build for Linux
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter build linux --release
        
      - name: Build for Windows
        if: matrix.platform == 'windows'
        run: flutter build windows --release

      - name: Build for iOS
        if: matrix.platform == 'ios'
        run: flutter build ios --release --no-codesign

      - name: Build for macOS
        if: matrix.platform == 'macos'
        run: flutter build macos --release

      - name: Build APK for release
        if: matrix.platform == 'android'
        run: flutter build apk --release

      # Upload artifacts steps would go here...

  finalize:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: 'android'
            artifact-name: 'android-app'
            artifact-path: 'build/app/outputs/flutter-apk/app-release.apk'
          - platform: 'linux'
            artifact-name: 'linux-app'
            artifact-path: 'build/linux/*'
          - platform: 'windows'
            artifact-name: 'windows-app'
            artifact-path: 'build/windows/x64/runner/Release/*'
          - platform: 'ios'
            artifact-name: 'iOS-app'
            artifact-path: 'build/ios/iphoneos/*.ipa'
          - platform: 'macos'
            artifact-name: 'macOS-app'
            artifact-path: 'build/macos/Build/Products/Release/*'

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}
